### ISSUE TITLE
Implement HRIA functionality

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#10]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/138
- [x] bcgov/BCHeritage/issues/175
- [x] bcgov/BCHeritage/issues/234

**Comment by bferguso** [comment]
Moving this to done as overall HRIA functionality complete.
