### ISSUE TITLE
Provide maps functionality currently done by GeoBC

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#102]
Overlay layers
Export shape & KML files
Filter by multiple layers
Need geology layers (look into current Bedrock Geology layer)
@elisabethdeom to get simplified geology layer from GeoBC 
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/103
- [ ] bcgov/BCHeritage/issues/104
- [x] bcgov/BCHeritage/issues/105
- [x] bcgov/BCHeritage/issues/106
- [x] bcgov/BCHeritage/issues/118

**Comment by bferguso** [comment]
Closing as KML export addressed in other issue.
