### ISSUE TITLE
1	Project details submission

### ISSUE THREAD

**Issue by Margee-BCGov** [bcgov/BCHeritage#1127]
[1. Project details submission.docx](https://github.com/user-attachments/files/17685092/1.Project.details.submission.docx)

- 7 steps - layout 2 days
- Specialized widgets
   - bcgov/bcrhp#92 (Shapefile/KML/GeoJSON only ? Or can users interact with widget?
   - [x] bcgov/BCHeritage#1172
   - [x] LOV component
   - [x] Date component
   - [ ] bcgov/BCHeritage#1173
   - [ ] Printable/PDF last page (1 day)
- [ ] Submission details validation (1 day)
- [ ] API endpoints (fetch, check unique across all, save) (1 day)
- [ ] Endpoint tests (1 day)

This will require analysis development of the following common components:
- [x] bcgov/BCHeritage#1155
- [x] bcgov/BCHeritage#1156
- [x] bcgov/BCHeritage#1161
- [x] bcgov/BCHeritage#1160
- [x] bcgov/BCHeritage#1159
- [x] bcgov/BCHeritage#1158
- [x] bcgov/bcrhp#92
- [x] bcgov/BCHeritage#1172
- [x] bcgov/BCHeritage#1164

**Comment by Margee-BCGov** [comment]
[1. Project details submission Nov22.docx](https://github.com/user-attachments/files/17952645/1.Project.details.submission.Nov22.docx)
Updated workflow definition

**Comment by bferguso** [comment]
All children completed. Closing
