### ISSUE TITLE
Clean site names

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#134]
Logical site names need to be created for each site. Currently only have detailed location and location description. Need to have a name, and geographic boundary for each site (and potentially sub-sites).
- [x] Provide spreadsheet with detailed_location, location_description, NTS mapsheet number, NTS mapsheet name, lat & long
- [x] Look into providing shapefile output with above data
- [ ] Create initial set of site geometries to send to local experts
- [ ] Send to local experts to group & name sites and subsites
- [ ] Upload new logical site names and boundaries into Arches
- [ ] Determine how to categorize one-off collection events (stand-alone site, group in geographic area (eg North-West), etc)?

**Comment by elisabethdeom** [comment]
Thanks
I will start with this

Elisabeth

**Comment by bferguso** [comment]
There is no existing grouping of logical sites so they need to be created within the system.
