### ISSUE TITLE
Create Resource Model for LG Site Submission

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#14]
Need to create a  Resource Model to replace the Local Government tracking spreadsheet. The spreadsheet is currently used to track what state Local Government submissions are in.

- [x] Heritage branch to review resource model
- [x] Heritage branch to supply help text information
- [ ] Heritage branch to define field level requirements (place holder text, character count, etc.)
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/15
- [x] bcgov/BCHeritage/issues/313
- [x] bcgov/BCHeritage/issues/334

**Comment by victoriacooper** [comment]
@bferguso Not sure if we have a requirement epic for this, though we do have some children issues by the looks of it. Think you could take a look, or it is easier to review multiple unknowns in one of our meetings?

**Comment by bferguso** [comment]
@victoriacooper - this is tied more closely to point 18 in the spreadsheet _Ability to review and either return submitted records to local government staff with comments, or to request updated records via the portal (iterative process)._

Currently the branch tracks the state of new submissions from LG and which/when an entry has been published to the CRHP in spreadsheets. We need to enable the branch to track the state of submissions and CRHP publications within the spreadsheet within the system so they can eliminate the manual spreadsheet processes. 

Eventually when LGs can submit on their own this may change a bit, but we should create the model with a view to this being the final goal. It is unlikely the publication to CRHP will change in any significant way in the foreseeable future, so that part may be a bit more static.

**Comment by bferguso** [comment]
Closing as outstanding issue handled in other issues.
