### ISSUE TITLE
Define business rules for taxonomy data entry

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#142]
Need to have a session to define what business rules are applied when entering taxonomic information
Outstanding Tasks after 27 September meeting:

_*Fossil Type Changes*_
- [x] Add common names to lookup (data load)
- [x] Update fossil type descriptors function to remove unused config html
- [x] Update fossil type descriptors function to show default size category and significance

_*Fossil Sample Changes*_
- [x] Create custom widget to layout taxon / connector / taxon horizontally moved to #279 
- [x] Allow for unlisted Genus before & after connector - single free-form text field for this and next
- [x] Allow for unlisted Species before & after connector
- [x] Generate readonly taxon string from individual elements - moved to #279 
- [x] Modify search so species show up when searching for associated genus string - moved to #279
