### ISSUE TITLE
Create Resource Model for LG submission tracking

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#15]
Create a Resource Model to replace the spreadsheet currently used to track the state of submissions by Local Governments. 
Questions:
- [x] When a BCRHP submission is made, do we want to identify the LG resource that submitted it? Or just the LG? - Identifying person that submitted it too
- [x] We need to track the LG resource (employee) -> LG
- [x] For submission types (CHR, HRA, HCA, etc) are these just for Additions?  - For all
CHR - Community Heritage Register
HCA - Heritage Conservation Area
HD - Heritage Designation
HRA - Heritage Revitalization Agreement

- [x] What are the definitions of the submission type acronyms (CHR, HRA, etc)?
- [x] What is the outcome of a "Heritage Register review"? Should this be a submission operation (eg Addition, Removal. Update)? -Probably not necessary. Eventually LG will review themselves
- [x] Should submission operation be assigned at the site level or remain at the submission level (eg - do you want to allow a submission that includes both Addition and Removal? - Moved to Site level for review
- [x] Should Submission Type (eg (CHR, HRA) be assigned at the site level or remain at the submission level? Looks like multiple Types  are allowed in a submission. Should those be assigned at the Site level so it's a 1:1? - Moved to Site level for review
- [x] Do we need to manually manage the "Mandatory | Optional fields missing/Corrections" fields or can we manage this with the BC Heritage Resource validation? - Don't need to track.
