### ISSUE TITLE
Add missing parts of HRIA data

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#173]
Need to add parts of HRIA that were not uploaded as part of the POC. Areas include:
- [x] Decision History
- [ ] Site children
- [ ] Register type
- [ ] Site images
- [ ] Site references
- [ ] Site condition
- [ ] Tenure
- [ ] Environmental
- [ ] Remarks
- [ ] Dimensions (do we actually want to import this?)
- [ ] Chronology - Need to discuss this. Not sure what this is about.
- [x] Heritage Class
- [ ] Heritage Theme
- [ ] Architect/Builder
- [ ] NTS reference (do we want to import this or just have that dynamic based on geometry?
- [ ] GIS History (?)
- [ ] Reference Year
