### ISSUE TITLE
Ability to import and export data in a variety of formats

### ISSUE THREAD

**Issue by victoriacooper** [bcgov/BCHeritage#261]
- [x] Confirm ability to export shapefiles
- [ ] Confirm ability to import shapefiles (post mvp?)
- [x] Confirm ability to export csv search results
- [x] Confirm ability to print out details pages
- [x] Confirm ability to convert shapefiles in ArcGIS to file format suitable for Arches

XML to Canadian Register covered under separate Epic #672
# Dependencies

## Epic

- [ ] bcgov/BCHeritage/issues/607
- [ ] bcgov/BCHeritage/issues/608
- [ ] bcgov/BCHeritage/issues/674
- [ ] bcgov/BCHeritage/issues/754

**Comment by emjohnst** [comment]
Removing mvp label as all mvp items are complete
