### ISSUE TITLE
General Public Access to BCRHP

### ISSUE THREAD

**Issue by victoriacooper** [bcgov/BCHeritage#296]
ACCESS TO VIEW DATA WILL BE OPEN, BUT THE FIELDS AVAILABLE TO VIEW WILL BE RESTRICTED BY HERITAGE BRANCH.

Public access will provide a better understanding of BC Heritage and for research

**_This needs to be available for public presentation May1-3._**

To be captured in additional tickets:
- Ability to view and export (but not edit) data fields on register database flagged as “Publish” from all layers of historic place information (e.g. historic trails, Heritage Conservation Areas, sites nominated for provincial recognition projects, etc.)
- Ability to search on any field in attribute list and search by ‘tags’.
- View information, images, media and documents about each site in a consistent format so that images, audio/visual clips of each site are available.. 
- See selected associated documents and other content about each site.
- Ability to suggest new sites for consideration and addition to database, also to provide comments and additional information and images (vetted by Branch staff) about existing sites.

**NOT PART OF MVP**
# Dependencies

## Epic

- [ ] bcgov/BCHeritage/issues/692
- [x] bcgov/BCHeritage/issues/693
- [x] bcgov/BCHeritage/issues/694 - tracked in epic 692
- [x] bcgov/BCHeritage/issues/695
- [x] bcgov/BCHeritage/issues/696 - tracked in epic 692
- [x] bcgov/BCHeritage/issues/697 - tracked in epic 692
- [ ] bcgov/BCHeritage/issues/698
- [ ] bcgov/BCHeritage/issues/699

**Comment by emjohnst** [comment]
Done in test
