### ISSUE TITLE
Share Borden Numbers with HRIA

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#3]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/224
- [x] bcgov/BCHeritage/issues/321
- [x] bcgov/BCHeritage/issues/690
- [x] bcgov/BCHeritage/issues/691
- [x] bcgov/BCHeritage/issues/719
- [x] bcgov/BCHeritage/issues/764

**Comment by victoriacooper** [comment]
Captured in requirement line 16, excel document: _Ability to continue use of the same Borden Number issuing function as Arch. Branch._

**Comment by bferguso** [comment]
Created test insert and ran it w/ Archeology branch. Outcome is:
1. Was successfully able to create site with next borden number in HRIA without associated geometry
2. New entry was visible from within the HRIA UI
3. Next site was successfully created from with HRIA UI
4. **_The borden number generated in 3 was not visible in the SDE schema. It is held in ESRI and is only pushed back into the HRIA SDE schema as part of a nightly batch process_**
5. In consulting with Arch IT group there appears to be an ESRI API that can be used to access the full set of Borden Numbers in the system.

Next steps:
1. Determine if there are licensing implications for accessing ESRI API from Arches
2. If outcome of license discussion is acceptable, get API documentation and credentials to perform follow-up test.

Options to move forward:
1. Lookup next Borden Number using ESRI API and create next entry in HRIA SDE schema without geometry
2. Lookup next Borden Number using ESRI API and create next entry using ESRI API (this will require creating a geometry).
3. If ESRI API not tenable, perform Borden Number generation in batches after nightly batch is run (currently starts at 10:30pm)
4. Last resort fallback is to generate skeleton record using HRIA UI
