### ISSUE TITLE
Publish BCRHP spatial data to BCGW

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#317]
- [x] Contact BCGW to determine how we can convey information to BCGW
- [x] Identify attribute data that needs to be published
- [x] Determine what layers need to be published: Historic Environment Layer
- [x] #708
- [ ] Ask BCGW (with Arch permission) to add updated Historic Environment Layer to RAAD
- [x] Ask BCGW to filter out historic sites by Yes or No flag from Archaeological sites layer of RAAD
- [x] Get new BCGW layers into ILRR

Post mvp: follow process to update layers for other data sets (conservation areas, trails, etc.)
# Dependencies

## Epic

- [ ] bcgov/BCHeritage/issues/318
- [ ] bcgov/BCHeritage/issues/708

**Comment by TMcFarland-Heritage** [comment]
Heritage layers that are on the BCGW and BC Data Catalogue and available on iMap for public users:
o	Heritage Conservation Areas of BC https://catalogue.data.gov.bc.ca/dataset/heritage-conservation-areas-of-bc 
o	Historic Environment View spatial layer https://catalogue.data.gov.bc.ca/dataset/historic-environment-spatial-layer 
o	Historic Trails of BC https://catalogue.data.gov.bc.ca/dataset/historic-trails-of-british-columbia-internal  

The 'Historic Environment View' layer also feeds into the Historic Places Web map on the BC Map Hub (available to public an government users). Ideally this should be maintained until the Arches BCRHP has a public access version. URL to historic places web map: https://governmentofbc.maps.arcgis.com/apps/webappviewer/index.html?id=4926e2fd04b6484ba47c3a8cd14202a0

**Comment by emjohnst** [comment]
Layer File Presentation for DataBC ticket requirements https://bcgov.github.io/data-publication/pages/dsg_bcgw_layer_file_presentation.html

Dataset model template [Dataset_Model_Current_TEMPLATE.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d7c898178859e5241ebb043dbb968aca3878929/Dataset_Model_Current_TEMPLATE.xlsx)

DataBC ticket # 2740
