### ISSUE TITLE
Updates to Site Report page

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#394]
- [ ] Split top to be ½ map ½ image? - BF - Not in MVP. Large structural change
- [ ] Discuss placement of image with Brett – HB would like the image more at the top of the site record, potentially sharing the top banner with the map BUT
- [ ] How would multiple images be displayed in this case?
- [ ] Less white space – not as long of a scroll, more compact information
- [ ] Side navigation of sections like what is available in editing page would be nice to have on view page (see below)
- [ ] Order of sections (Should we discuss - current order is in the logical order of data entry)
1. Borden Number
1. Site Name
1. Address
1. Legal description
1. BC Right
1. BC Statement of Significance
1. BC Heritage Class
1. BC Heritage Theme
1. BC Heritage Function
1. Related Resources
1. URL
1. Remarks – not for public
1. Decision History – not for public

- [x] Rename `BC Heritage Resource` to `Heritage Site`
- [x] Site Names > Name Type Drop Down > Primary/Alternative / Rename “Common/Other”
- [x] BC Heritage Resource Place Heading / Rename `Heritage Site Location`
- [x] Spatial Location > Remove Geodetic Datum
- [x] Remove "Geometry Qualifier" EJB - doesn't the spatial geometry box list whether its a polygon or point? So this seems like a redundant field to me unless I'm missing something.
- [ ] #561
- [x] BC Property Address > Street Number & Street Name > Combine fields (#535)
- [x] City Create drop down list BF: After discussion perhaps we do address validation (see #535)? EJB: Yes
- [x] Civic Address Notes > Rename “Location Description”. 
- [x] #609
- [x] Description Location > Remove Field/Card
- [x] Official Recognition Information > Registry Types - Update LOV
- [x] Official Recognition Information > Add “Registration Status" (#552). Confirm where this field was added.
- [ ] ~Official Recognition Information > Move Official Recognition Details to Official Recognition Information Page card~ - BF - Can't do this as the cardinality does not match
- [x] Designation or Protection From Date > Rename “Designation or Protection Start Date”
- [x] Designation or Protection To Date > Rename “Designation or Protection End Date”
- [x] Responsible Government > Rename “Government Name”
- [x] Description > Rename “Notes” BF - Do we want this to be an RTF? EJB: Yes
- [x] BC Heritage Class Heading > Rename “Heritage Class”
- [x] Contributing Resource Count > Rename “Number of Contributing Resources”
- [x] BC Heritage Function Heritage > Rename “Heritage Function” 
- [x] BC Heritage Theme > Rename "Heritage Theme"
- [x] Functional Category > Rename “Heritage Function” Merge listings so Headings are listed in front of each subheading by a colon. For example: Commerce / Commercial Services: Bank or Stock Exchange. Error: There is repetition in this list for example Religion, Ritual and Funeral and subtypes is listed twice. #562
- [x] BC Heritage Theme > Remove “Theme Comments” field - There are 6 values in HRIA. Should we disregard them? EJB: Can you send the data to me to verify?
- [x] Heritage Theme > Make same merge change as Heritage Function above #562
- [x] Architects / Builders > Remove “Comments” field - There are 83 values in HRIA. Should we disregard them? EJB: Can you send the data to me to verify?. Updated: Decided not to remove.
- [x] Significant Events > Rename “Chronology”
- [x] Start Year/End Year > Error: seems like a glitch when selecting year then month date?
- [x] End Year > Move field beside “Start Year” Field EJB - let's remove this if it can't be done
- [x] EJB Update: Start Year Qualifier / End Year > Remove
- [x] EJB Update: "Event" drop down Add> "Construction (circa)" and "Significant (circa)"
- [x] #556
- [x] Statement of Significance - Move “Significance Description” up, after “Heritage Value Field” (#501)
- [x] Rename "Significance Description" to "Description" (it's a physical description of the site)
- [x] Defining Elements > Rename “Character-Defining Elements”
- [x] Site Images > Rename “Images”
- [x] Images > Edit> Add “Primary Image” toggle button
- [x] Images > Edit > Add "Submit to CRHP" toggle button
- [x] #557
- [x] #558
- [x] Remove “Image Title” - There are 5395 images with titles, 11 with 2 titles EJB - move these to "Image Caption"
- [x] Image Description > Rename “Image Caption” (source column is "title")
- [x] Additional Descriptions > Rename “Image Description”– (include old desc text in data transfer), Put multiple source "descriptions" field in here, and any extra titles.
- [ ] ~Image type > Remove drop down options and add instead: 1. Contemporary Photograph; 2. Historic Image; 3. Other. BF - there is data matching the image types. Do we want to lose this?~ Addressed in #559
- [ ] #559
- [x] Site Document Heading > Rename “Documents”
- [x] Remove “Documents Format” Field
- [x] External URLS - Remove “External URL Description” field - BF - Moved data to `Link Text` part of URL.
- [x] Create Missing Field to link to QA type where we can change from “Provisional” to “Authoritative” Can we create Record Entry Status toggle that is automatically set to Provisional until it’s ready to be manually set when reviewed? - BF - This is built-in functionality in Arches. There shouldn't be anything we need to do. Perhaps we should go through what it looks like in a meeting to clarify.
- [ ] ~Authoritative > Rename “Verified”~ Part of base Arches functionality
- [ ] Site submission status [#575](https://app.zenhub.com/workspaces/bcheritage-arches-6201b29ea2749e00146fb636/issues/gh/bcgov/bcheritage/575)
- [x] EJB Update: Remove from BC Property Address "Cadastral Reference" since this was where we were going to put PID but there's already a PID field under legal description
- [x] Add "Site Form" to Document Type

**Comment by bferguso** [comment]
Using the document provided.

**Comment by bferguso** [comment]
Moving this to Completed in Dev as all outstanding tasks seem to be covered by other issues.
