### ISSUE TITLE
BC Fossil Contributor - edits and mandatory attributes to mark

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#434]
- [x] Company or Individual* - already marked 
- [x] Company or Individual rename to Organization or Individual
- [x] Role – mark as mandatory
- [x] Contact Email – mark as mandatory - BF: made mandatory but asterisk not showing
- [x] Contact Phone Number – mark as mandatory - BF: made mandatory but asterisk not showing
- [x] Company Name - delete. Use Last name field
- [x] ~Move “Company Name” up ~ - Removing field
- [ ] Rule: If click “Individual”, then “Associated Company” will appear, but be optional
- [] ~Associated Company has some individual names listed here~ - BF - This is due to the fuzzy logic of the load marking individual with long names as Organizations
- [x] Change “Add new Relationship” to “Select Company Name if applicable” - BF - Dependent on framework change. 
- [x] #487
- [x] Last Name – mark as mandatory - BF: made mandatory but asterisk not showing
- [x] First Name – mark as mandatory - BF: Needs conditional logic as not mandatory for organizations
- [x] Start Date – delete 
--what is languages box here?

**Comment by LeannePyle** [comment]
We addressed these items within the Research Permit ticket

**Comment by bferguso** [comment]
@LeannePyle  - Typically in these types of forms the name is entered before contact information. Are you sure you want to list the information in this order?

**Comment by LeannePyle** [comment]
Agree- name before contact information looks better
