### ISSUE TITLE
BC Fossil Site - edits and mandatory attributes to mark

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#438]
- [x] Fossil Site Name – mark as mandatory
- [x] Spatial Location – mark as mandatory
- [x] In this page – Geometry Qualifier not working on this page 
- [x] --move Site Notes down in list below Location
- [ ] ~Fossil Sub-sites – delete~ - BF: This is required for the site hierarchy previously requested. As per discussion w/ Leanne 2023-05-30 leaving in.
- [x] #474 - To be addressed post-mvp when other groups added to system.
