### ISSUE TITLE
Industry Project Assessment - mandatory attributes to mark

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#439]
- [x] Project Initiator
- [x] Project Authorizing Agency
- [x] Project Type
- [x] Proposed Activity
- [x] Location Description
- [x] Spatial Location
- [x] Assessment Start Date

(under Initial Project Review) - BF: Will all of these be known all at once?

- [x] Intersects with Important Fossil Area
- [x] In Proximity to Fossils
- [x] Ground Disturbance
- [x] Quaternary deposits
- [x] Sedimentary rock
- [x] Igneous rock
- [x] Metamorphic rock
- [x] FRPR
- [x] Initial Review Level of Risk

(under PSR)

- [x] Lead Paleontology Consultant
- [x] PSR Title
- [x] PSR Number

(under Site Assessment Plan)

- [x] --need to change all IMP to SAP here
- [x] SAP Paleontology Consultant – spell out Paleontology
- [x] SAP Title
- [x] SAP Report Number

(under FIA Report)

- [x] Lead Paleontology Consultant
- [x] FIA Report Title
- [x] FIA Report Number

(under FIA Plan Report)

- [x] Lead Paleontology Consultant
- [x] FIA Plan Report Title
- [x] FIA Plan Report Number
- [x] --reorder to have Title come before Number

(under Chance Find Protocol)

- [x] --add Chance Find Protocol Title – make mandatory

(under Impact Mitigation Plan)

- [x] IMP Paleontology Consultant - spell out Paleontology
- [x] IMP Title
- [x] IMP Report Number
