### ISSUE TITLE
Setup S3 Object Storage

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#442]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/443
- [x] bcgov/BCHeritage/issues/444
- [x] bcgov/BCHeritage/issues/445
- [x] bcgov/BCHeritage/issues/446
- [x] bcgov/BCHeritage/issues/447
- [x] bcgov/BCHeritage/issues/448
