### ISSUE TITLE
Geological Age ordering

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#480]
Geological Age
    - [ ] Rule: If “Age undetermined is checked, other field on page are not visible to inputter” No ability to chain widgets (#470)
    - [ ] Historical Value – if stays visible, state “for FMO use only” BF: No ability to chain widgets (#470). Visibility to be handled post-MVP
    - [ ] Stratigraphy – when in menu for Group, you can pick anything – can we make all visible but just Group pickable? Same for Formations BF: No ability to chain widgets (#470).
