### ISSUE TITLE
Create Fossils Business Model

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#6]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/33
- [x] bcgov/BCHeritage/issues/65
- [x] bcgov/BCHeritage/issues/71
- [x] bcgov/BCHeritage/issues/78
- [x] bcgov/BCHeritage/issues/79
- [x] bcgov/BCHeritage/issues/81
- [x] bcgov/BCHeritage/issues/149
- [x] bcgov/BCHeritage/issues/192
- [ ] bcgov/BCHeritage/issues/197
- [x] bcgov/BCHeritage/issues/199

**Comment by bferguso** [comment]
Marking as complete. Ontology classes can be handled at a later date if desired. That should be a low priority.
