### ISSUE TITLE
Import historic HRIA Arch data

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#645]
Legacy Site Details
# Dependencies

## Epic

- [ ] bcgov/BCHeritage/issues/646
- [ ] bcgov/BCHeritage/issues/652
- [ ] bcgov/BCHeritage/issues/653
- [ ] bcgov/BCHeritage/issues/654
- [ ] bcgov/BCHeritage/issues/655
- [ ] bcgov/BCHeritage/issues/656
- [ ] bcgov/BCHeritage/issues/657
- [ ] bcgov/BCHeritage/issues/658
- [ ] bcgov/BCHeritage/issues/734
