### ISSUE TITLE
BCRHP Resource Models Verification

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#670]
- [ ] Complete tickets related to resource models
- [ ] Heritage branch to verify resource model is complete
# Dependencies

## Epic

- [ ] bcgov/BCHeritage/issues/552
- [ ] bcgov/BCHeritage/issues/530
- [ ] bcgov/BCHeritage/issues/559
- [ ] bcgov/bcrhp#91
- [ ] bcgov/BCHeritage/issues/575
- [ ] bcgov/BCHeritage/issues/597
- [ ] bcgov/BCHeritage/issues/642
- [ ] bcgov/BCHeritage/issues/689
- [ ] bcgov/BCHeritage/issues/701
- [ ] bcgov/BCHeritage/issues/703
- [ ] bcgov/BCHeritage/issues/704
- [ ] bcgov/BCHeritage/issues/705
- [ ] bcgov/BCHeritage/issues/711
- [ ] bcgov/BCHeritage/issues/721
- [ ] bcgov/BCHeritage/issues/733
- [ ] bcgov/BCHeritage/issues/735
- [ ] bcgov/BCHeritage/issues/736
- [ ] bcgov/BCHeritage/issues/737
- [x] bcgov/BCHeritage/issues/752
