### ISSUE TITLE
BCRHP Data Cleaning & Verification

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#671]
# Dependencies

## Epic

- [x] ~bcgov/BCHeritage/issues/396~ - Post MVP
- [x] bcgov/BCHeritage/issues/504
- [x] bcgov/BCHeritage/issues/561
- [x] bcgov/BCHeritage/issues/573
- [x] bcgov/BCHeritage/issues/648
- [x] bcgov/BCHeritage/issues/673
- [x] bcgov/BCHeritage/issues/739
- [x] bcgov/BCHeritage/issues/765

**Comment by bferguso** [comment]
Moving to QA as all sub-tasks seem to be complete (or at least in QA)
