### ISSUE TITLE
Canadian Register CRHP Export

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#672]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/87
- [x] bcgov/BCHeritage/issues/572
- [ ] ~bcgov/BCHeritage/issues/576~

**Comment by emjohnst** [comment]
Emailed XSD files to @bferguso

**Comment by bferguso** [comment]
Image packaging not part of MVP - will handle as separate issue. Moving to QA
