### ISSUE TITLE
Final prep for BCRHP MVP

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#686]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/671
- [x] bcgov/BCHeritage/issues/687
- [x] bcgov/BCHeritage/issues/688
- [x] bcgov/BCHeritage/issues/739
