### ISSUE TITLE
UI Modifications for Public Access

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#692]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/718
- [x] #694
- [x] bcgov/BCHeritage/issues/886
- [x] #887
- [ ] #889 moved to post mvp 2
- [x] #890
- [x] #891
- [x] #892
- [x] #893
- [x] #696 

- [x] https://github.com/bcgov/BCHeritage/issues/636
- [x]  https://github.com/bcgov/BCHeritage/issues/665
- [x]  https://github.com/bcgov/BCHeritage/issues/666
- [ ] https://github.com/bcgov/BCHeritage/issues/697 no longer applicable

**Comment by bferguso** [comment]
Moving estimates to sub-issues for more detailed estimates

**Comment by emjohnst** [comment]
Done in test
