### ISSUE TITLE
Provide access via public URL

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#699]
- [x] vanity url - simple bcrhp acronym
- [x] Decide if url is to separate public site or not

Multiple context roots (`/int/bcrhp` and `/pub/bcrhp`) appears that it will be problematic. Navigation within the app appears to be tied to this context root. Possibilities to investigate:
- [x] Use common URL and implement OAuth 2.0 to provide standard authentication login button.
- [ ] ~Have 2 separate deployed instances, using a common database/elasticsearch to allow different URLs (int, pub)~
- [ ] ~Is there a way to externalize the context root everywhere so that the entry point (int or pub) can be persisted throughout the app?~
- [ ] ~Another interface w/ SiteMinder that can have a common URL?~
- [ ] ~Federated SiteMinder?~ BC Registries OIDC

Moving forward with SSO OIDC implementation. URL to be https://[instance]apps.nrs.gov.bc.ca/bcrhp. Steps to proceed:
- [x] Request reverse proxy updates from NRIDS
- [x] Request application SSO configuration (self-serve)
- [x] #908
- [x] #909
- [x] #910

**Comment by bferguso** [comment]
Determined that using legacy SiteMinder (/int/, /pub/) is going to be problematic to be able to use single deployed app. Moving forward wth implementing Pathfinder SSO. Proposed URL for both internal and external access will be https://apps.nrs.gov.bc.ca/bcrhp.

Requested reverse proxy configuration from NRIDS today and started SSO request for DLVR. Once the reverse proxy work has been completed we can complete the SSO request and move forward with the development of the updated configuration.

**Comment by emjohnst** [comment]
Done in test
