### ISSUE TITLE
Application Styling for BCRHP site

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#75]
Minor updates to model, card information, and general layout of the BCRHP implementation
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/36
- [x] bcgov/BCHeritage/issues/235
- [x] bcgov/BCHeritage/issues/345
- [x] bcgov/BCHeritage/issues/391
- [x] bcgov/BCHeritage/issues/392
- [x] bcgov/BCHeritage/issues/393
- [x] bcgov/BCHeritage/issues/394
- [x] bcgov/BCHeritage/issues/484
- [x] bcgov/BCHeritage/issues/592
- [x] bcgov/BCHeritage/issues/594
- [x] bcgov/BCHeritage/issues/628
- [x] bcgov/BCHeritage/issues/632
- [x] bcgov/BCHeritage/issues/636
- [x] bcgov/BCHeritage/issues/665
- [x] bcgov/BCHeritage/issues/666

**Comment by victoriacooper** [comment]
@bferguso is this essentially "design" for the application? Assuming so based on the related issue above.

**Comment by bferguso** [comment]
@victoriacooper - Yes - this is a placeholder for any changes necessary for overall look and feel requirements.

**Comment by emjohnst** [comment]
Done in test
