### ISSUE TITLE
Add notes fields to resource models

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#79]
- [x] Fossil Site
- [x] Collection Event -- Left as is for now until we review the descriptions branch
- [x] Fossil Samples
- [x] Storage locations

Should there be an "Internal Notes" for each that are private and never shared with public / external resources?

Note types as follows:
- [x] Fossil Site: Used default Description Type for now. Needs revisiting.
- [x] Collection Event: Field Notes, Office Notes, others? (Created initial vocab with first two, if others needed, create new issue)
- [x] Fossil Samples: See #129
- [x] Storage Locations: Used default Description Type for now. Needs revisiting.
- [x] Fossil Sample -> Storage Location relationship. Created initial list including Additional Location Notes and Others.

**Comment by bferguso** [comment]
@elisabethdeom - Should we be supporting multiple languages for this?

**Comment by bferguso** [comment]
If we use description types, need to define initial set of values (one per resource?), eg Notes, Summary, Overview, Internal Notes, etc.

**Comment by bferguso** [comment]
Collection Event - Fields Notes, Office Notes, others?
@elisabethdeom  - Can you please provide lists for each resource type.

**Comment by bferguso** [comment]
@elisabethdeom - Assigning to you for list of note types

**Comment by bferguso** [comment]
Closing this out as it has been lingering too long. Created new issues for the two note types that have not been addressed (BC Fossil Site and BC Fossil Storage Location).
