### ISSUE TITLE
Provision PROD server

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#804]
# Dependencies

## Epic

- [x] bcgov/BCHeritage/issues/683
- [x] bcgov/BCHeritage/issues/685
- [x] bcgov/BCHeritage/issues/726
- [x] bcgov/BCHeritage/issues/801
- [x] bcgov/BCHeritage/issues/802
- [x] bcgov/BCHeritage/issues/803
- [x] bcgov/BCHeritage/issues/805
- [x] bcgov/BCHeritage/issues/806
- [x] Have NRIDS make ENDOWMENT self-signed certificates trusted (DLVR & TEST) by server and get names used in the certificate
- [x] Have NRIDS make EARLY self-signed certificate trusted by server and get names used in the certificate

**Comment by bferguso** [comment]
Requested NRIDS to make self-signed certs trusted by servers.

**Comment by bferguso** [comment]
Completed.
